// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	appDir: () => typedError<string, string>(__TAURI_INVOKE("app_dir")),
	// 是否通过应用商店类渠道安装（内置更新应关闭）。具体判断在 `utils/app_store.rs`。
	isAppStore: () => __TAURI_INVOKE<boolean>("is_app_store"),
	testConn: (conf: ConnConfig) => typedError<null, string>(__TAURI_INVOKE("test_conn", { conf })),
	masters: (conf: ConnConfig) => typedError<{ [key in string]: string }[], string>(__TAURI_INVOKE("masters", { conf })),
	connList: (connList: ConnConfig[]) => typedError<null, string>(__TAURI_INVOKE("conn_list", { connList })),
	connect: (id: string) => typedError<ServerCapabilities, string>(__TAURI_INVOKE("connect", { id })),
	disconnect: (id: string) => typedError<null, string>(__TAURI_INVOKE("disconnect", { id })),
	dbList: (id: string) => typedError<RedisDB[], string>(__TAURI_INVOKE("db_list", { id })),
	selectDb: (id: string, db: number) => typedError<null, string>(__TAURI_INVOKE("select_db", { id, db })),
	info: (id: string, node: string | null) => typedError<RedisInfo, string>(__TAURI_INVOKE("info", { id, node })),
	infoList: (id: string) => typedError<RedisInfo[], string>(__TAURI_INVOKE("info_list", { id })),
	chart: (id: string, node: string | null) => typedError<RedisChart, string>(__TAURI_INVOKE("chart", { id, node })),
	chartList: (id: string) => typedError<RedisChart[], string>(__TAURI_INVOKE("chart_list", { id })),
	nodeList: (id: string) => typedError<RedisNode[], string>(__TAURI_INVOKE("node_list", { id })),
	scan: (id: string, param: ScanParam) => typedError<ScanResult_Serialize, string>(__TAURI_INVOKE("scan", { id, param })),
	fieldScan: (id: string, param: FieldScanParam_Deserialize) => typedError<FieldScanResult, string>(__TAURI_INVOKE("field_scan", { id, param })),
	ttl: (id: string, key: RedisKey_Deserialize, ttl: number) => typedError<null, string>(__TAURI_INVOKE("ttl", { id, key, ttl })),
	set: (id: string, param: RedisSetParam_Deserialize) => typedError<null, string>(__TAURI_INVOKE("set", { id, param })),
	del: (id: string, key: RedisKey_Deserialize) => typedError<null, string>(__TAURI_INVOKE("del", { id, key })),
	rename: (id: string, key: RedisKey_Deserialize, newKey: RedisKey_Deserialize) => typedError<RedisKey_Serialize, string>(__TAURI_INVOKE("rename", { id, key, newKey })),
	fieldAdd: (id: string, param: RedisFieldAdd) => typedError<RedisKey_Serialize, string>(__TAURI_INVOKE("field_add", { id, param })),
	fieldSet: (id: string, param: RedisFieldSet_Deserialize) => typedError<null, string>(__TAURI_INVOKE("field_set", { id, param })),
	fieldDel: (id: string, param: RedisFieldDel_Deserialize) => typedError<null, string>(__TAURI_INVOKE("field_del", { id, param })),
	executeCommand: (id: string, param: RedisCommand) => typedError<string, string>(__TAURI_INVOKE("execute_command", { id, param })),
	slowLog: (id: string, count: number | null, node: string | null) => typedError<RedisSlowLog[], string>(__TAURI_INVOKE("slow_log", { id, count, node })),
	memoryUsage: (id: string, param: RedisMemoryParam) => typedError<RedisKeySize_Serialize[], string>(__TAURI_INVOKE("memory_usage", { id, param })),
	configGet: (id: string, pattern: string, node: string | null) => typedError<{ [key in string]: string }, string>(__TAURI_INVOKE("config_get", { id, pattern, node })),
	configSet: (id: string, key: string, value: string, node: string | null) => typedError<null, string>(__TAURI_INVOKE("config_set", { id, key, value, node })),
	clientList: (id: string, node: string | null, clientType: string | null) => typedError<RedisClientInfo[], string>(__TAURI_INVOKE("client_list", { id, node, clientType })),
	publish: (id: string, channel: string, message: string) => typedError<null, string>(__TAURI_INVOKE("publish", { id, channel, message })),
	subscribe: (id: string, channel: string | null) => typedError<null, string>(__TAURI_INVOKE("subscribe", { id, channel })),
	subscribeStop: (id: string) => typedError<null, string>(__TAURI_INVOKE("subscribe_stop", { id })),
	monitor: (id: string, node: string) => typedError<null, string>(__TAURI_INVOKE("monitor", { id, node })),
	monitorStop: (id: string) => typedError<null, string>(__TAURI_INVOKE("monitor_stop", { id })),
	batchDel: (id: string, param: RedisBatchKey_Deserialize) => typedError<null, string>(__TAURI_INVOKE("batch_del", { id, param })),
	batchTtl: (id: string, param: RedisBatchTtl_Deserialize) => typedError<null, string>(__TAURI_INVOKE("batch_ttl", { id, param })),
	exportCsv: (id: string, param: RedisExportCsv_Deserialize) => typedError<null, string>(__TAURI_INVOKE("export_csv", { id, param })),
	importCsv: (id: string, param: RedisImportCsv) => typedError<null, string>(__TAURI_INVOKE("import_csv", { id, param })),
	importCmd: (id: string, file: string) => typedError<null, string>(__TAURI_INVOKE("import_cmd", { id, file })),
	mockData: (id: string, count: number) => typedError<null, string>(__TAURI_INVOKE("mock_data", { id, count })),
	keyType: (id: string, key: RedisKey_Deserialize) => typedError<string, string>(__TAURI_INVOKE("key_type", { id, key })),
	xinfoGroups: (id: string, key: RedisKey_Deserialize) => typedError<XInfoGroup[], string>(__TAURI_INVOKE("xinfo_groups", { id, key })),
	xinfoConsumers: (id: string, key: RedisKey_Deserialize, group: string) => typedError<XInfoConsumer[], string>(__TAURI_INVOKE("xinfo_consumers", { id, key, group })),
	keySlot: (id: string, key: RedisKey_Deserialize) => typedError<number, string>(__TAURI_INVOKE("key_slot", { id, key })),
	keyNode: (id: string, key: RedisKey_Deserialize) => typedError<RedisNode[], string>(__TAURI_INVOKE("key_node", { id, key })),
	flushDb: (id: string) => typedError<null, string>(__TAURI_INVOKE("flush_db", { id })),
	flushAll: (id: string) => typedError<null, string>(__TAURI_INVOKE("flush_all", { id })),
};

/* Types */
export type ConnConfig = {
	id: string,
	name: string,
	host: string,
	port: number,
	username: string,
	password: string,
	db: number,
	cluster: boolean,
	ssl: boolean,
	sslOption: SslOption,
	sentinel: boolean,
	sentinelOption: SentinelOption,
	ssh: boolean,
	sshOption: SshOption,
};

// 数据显示格式
export type DisplayFormat = "utf8" | "hex" | "binary" | "base64";

export type FieldScanParam = FieldScanParam_Serialize | FieldScanParam_Deserialize;

export type FieldScanParam_Deserialize = {
	key: RedisKey_Deserialize,
	hashKey: string | null,
	count: number,
	cursor: ScanCursor | null,
	loadAll: boolean,
	meta: FiledScanMeta | null,
	displayFormat: DisplayFormat | null,
};

export type FieldScanParam_Serialize = {
	key: RedisKey_Serialize,
	hashKey: string | null,
	count: number,
	cursor: ScanCursor | null,
	loadAll: boolean,
	meta: FiledScanMeta | null,
	displayFormat: DisplayFormat | null,
};

export type FieldScanResult = {
	type: string,
	ttl: number,
	size: number,
	value: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never },
	cursor: ScanCursor,
	length: number,
};

export type FiledScanMeta = {
	maxId: string,
	minId: string,
};

export type RedisBatchKey = RedisBatchKey_Serialize | RedisBatchKey_Deserialize;

export type RedisBatchKey_Deserialize = {
	match: string,
	keyList: RedisKey_Deserialize[],
};

export type RedisBatchKey_Serialize = {
	match: string,
	keyList: RedisKey_Serialize[],
};

export type RedisBatchTtl = RedisBatchTtl_Serialize | RedisBatchTtl_Deserialize;

export type RedisBatchTtl_Deserialize = {
	keyList: RedisKey_Deserialize[],
	ttl: number,
};

export type RedisBatchTtl_Serialize = {
	keyList: RedisKey_Serialize[],
	ttl: number,
};

export type RedisChart = {
	node: string,
	keyTotal: number,
	connectedClients: number,
	instantaneousOpsPerSec: number,
	usedMemory: number,
	instantaneousInputKbps: number,
	instantaneousOutputKbps: number,
	totalConnectionsReceived: number,
	totalCommandsProcessed: number,
	keyspaceHits: number,
	keyspaceMisses: number,
	cacheHitRatio: number,
};

export type RedisClientInfo = {
	id: string | null,
	addr: string | null,
	laddr: string | null,
	fd: string | null,
	name: string | null,
	age: string | null,
	idle: string | null,
	flags: string | null,
	db: string | null,
	sub: string | null,
	psub: string | null,
	ssub: string | null,
	multi: string | null,
	watch: string | null,
	qbuf: string | null,
	qbufFree: string | null,
	argvMem: string | null,
	multiMem: string | null,
	obl: string | null,
	oll: string | null,
	omem: string | null,
	totMem: string | null,
	events: string | null,
	cmd: string | null,
	user: string | null,
	redir: string | null,
	resp: string | null,
	rbp: string | null,
	rbs: string | null,
	ioThread: string | null,
};

export type RedisCommand = {
	command: string,
	node: string | null,
	autoBroadcast: boolean | null,
};

export type RedisDB = {
	db: number,
	size: number,
};

export type RedisExportCsv = RedisExportCsv_Serialize | RedisExportCsv_Deserialize;

export type RedisExportCsv_Deserialize = {
	match: string,
	keyList: RedisKey_Deserialize[],
	file: string,
	withTtl: boolean,
};

export type RedisExportCsv_Serialize = {
	match: string,
	keyList: RedisKey_Serialize[],
	file: string,
	withTtl: boolean,
};

export type RedisFieldAdd = {
	key: string,
	mode: string,
	type: string,
	ttl: number,
	value: string,
	inputFormat: DisplayFormat | null,
	listPushMethod: string,
	fieldValueList: RedisFieldValue[],
	streamId: string,
};

export type RedisFieldDel = RedisFieldDel_Serialize | RedisFieldDel_Deserialize;

export type RedisFieldDel_Deserialize = {
	key: RedisKey_Deserialize,
	fieldIndex: number,
	fieldKey: string,
	fieldValue: string,
	streamId: string,
};

export type RedisFieldDel_Serialize = {
	key: RedisKey_Serialize,
	fieldIndex: number,
	fieldKey: string,
	fieldValue: string,
	streamId: string,
};

export type RedisFieldSet = RedisFieldSet_Serialize | RedisFieldSet_Deserialize;

export type RedisFieldSet_Deserialize = {
	key: RedisKey_Deserialize,
	srcFieldValue: string,
	fieldIndex: number,
	fieldKey: string,
	fieldValue: string,
	fieldScore: number,
	fieldTtl: number,
	inputFormat: DisplayFormat | null,
};

export type RedisFieldSet_Serialize = {
	key: RedisKey_Serialize,
	srcFieldValue: string,
	fieldIndex: number,
	fieldKey: string,
	fieldValue: string,
	fieldScore: number,
	fieldTtl: number,
	inputFormat: DisplayFormat | null,
};

export type RedisFieldValue = {
	fieldKey: string,
	fieldValue: string,
	fieldScore: number,
	fieldTtl: number,
};

export type RedisImportCsv = {
	file: string,
	ttl: number,
	handleTtl: string,
	handleConflict: string,
};

export type RedisInfo = {
	node: string,
	info: string,
};

export type RedisKey = RedisKey_Serialize | RedisKey_Deserialize;

export type RedisKeySize = RedisKeySize_Serialize | RedisKeySize_Deserialize;

export type RedisKeySize_Deserialize = {
	key: string,
	bytes: string,
	type: string,
	size: number,
};

export type RedisKeySize_Serialize = {
	key: string,
	bytes: string,
	type: string,
	size: number,
};

export type RedisKey_Deserialize = {
	key: string,
	bytes: string,
};

export type RedisKey_Serialize = {
	key: string,
	bytes: string,
};

export type RedisMemoryParam = {
	match: string | null,
	sizeLimit: number,
	countLimit: number,
	scanCount: number,
	scanTotal: number,
	sleepMillis: number,
	needKeyType: boolean | null,
};

export type RedisNode = {
	id: string,
	node: string,
	flags: string,
	slots: string | null,
	slaveOfNode: string | null,
};

export type RedisSetParam = RedisSetParam_Serialize | RedisSetParam_Deserialize;

export type RedisSetParam_Deserialize = {
	key: RedisKey_Deserialize,
	value: string,
	ttl: number,
	keyType: string | null,
	inputFormat: DisplayFormat | null,
};

export type RedisSetParam_Serialize = {
	key: RedisKey_Serialize,
	value: string,
	ttl: number,
	keyType: string | null,
	inputFormat: DisplayFormat | null,
};

export type RedisSlowLog = {
	node: string,
	id: number,
	time: string,
	client: string,
	command: string,
	cost: number,
	clientName: string,
};

export type ScanCursor = {
	readyNodes: string[],
	nowNode: string,
	nowCursor: number,
	streamCursor: string,
	finished: boolean,
};

export type ScanParam = {
	match: string,
	count: number,
	type: string | null,
	cursor: ScanCursor | null,
	loadAll: boolean,
};

export type ScanResult = ScanResult_Serialize | ScanResult_Deserialize;

export type ScanResult_Deserialize = {
	keyList: RedisKey_Deserialize[],
	cursor: ScanCursor,
};

export type ScanResult_Serialize = {
	keyList: RedisKey_Serialize[],
	cursor: ScanCursor,
};

export type SentinelOption = {
	masterName: string,
	masterUsername: string,
	masterPassword: string,
};

export type ServerCapabilities = {
	hashFieldTtl: boolean,
};

export type SshOption = {
	host: string,
	port: number,
	loginType: string,
	username: string,
	password: string,
	pkfile: string,
	passphrase: string,
};

export type SslOption = {
	key: string,
	cert: string,
	ca: string,
};

export type XInfoConsumer = {
	name: string,
	pending: number,
	idle: number,
};

export type XInfoGroup = {
	name: string,
	consumers: number,
	pending: number,
	lastDeliveredId: string,
	entriesRead: number | null,
	lag: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

