name: sync-release-to-gitee

on:
  push:
    branches:
      - sync-release-to-gitee

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync GitHub Release to Gitee
        uses: trustedinster/sync-release-gitee@v1.1
        with:
          gitee_owner: hepengju
          gitee_repo: redis-me
          gitee_token: ${{ secrets.GITEE_TOKEN }}
          github_owner: hepengju
          github_repo: redis-me
          gitee_upload_retry_times: 3
          debug: false